pool:
  vmImage: 'windows-2022'

trigger:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

pr: 
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

steps:
  - checkout: self
    clean: 'true'

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.6.8'

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml
    displayName: Use GitVersion

  - task: MSBuild@1
    inputs:
      solution: src/Uno.CodeGen.sln
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\vslatest" "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%" /detailedsummary
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: VisualStudioTestPlatformInstaller@1

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*test*.dll
        !**\obj\**
      vsTestVersion: toolsInstaller
      testSelector: testAssemblies

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: $(Build.DefinitionName)
